### ISSUE TITLE
[Suggestion] More constants and a glyph for (the variable casting from special-behavior items produces)

### ISSUE THREAD

**Issue by Tysos24** [enjarai/trickster#63]
First, having only two constants, 2 and an empty list, makes it inconvenient to use hard-coded values. If I want to use a specific vector (3, 0, 0) for every cast, I need to: make an empty list, add a 2 to it, get the length of that list, add 2 to that, and finally create a vector with the resulting three and two zeros I have to make by reading the length of more empty lists. A few more constants would be nice.

Second, a glyph made to function as… a variable (I guess?) for the more specialized types of casting. For example, when you attack with a tool or sword. The attacked entity is used as an “input” for the spell, but many ploys - likely what’ll be used in such a scenario - take multiple inputs, and there’s no way to specify where that entity is input (that I know of). A specific glyph that means “the input” could solve that issue.

**Comment by StellarWitch7** [comment]
Lists were not intended for acquiring an arbitrary number... that's a clever way of doing that! The lack of constants is intentional. There are many ways to create literal values from the number 2, which you may then save in *any* item, and later embed in a spell with only a single revision (see the end of the section on spell scribing). #62 will also add the possibility of easily referencing these constants when editing a spell, and it's getting pretty close to a state where it can be merged.

Regarding your second point, you may want to read the section in tricks/delusions-ingresses/arguments? I'm fairly sure it's what you're referencing here.

If you have any more questions, you're free to drop them here or ask in the Discord!

**Comment by Tysos24** [comment]
I get it now, though I wasn’t sure what those arguments actually meant from the book’s explanation.
